package main

import (
	"time"
)

func main() {
	player, err := NewPlayer(44100)
	if err != nil {
		panic(err)
	}
	defer player.Close()

	var (
		c = 220.0
		d = c * (1 + 1.0/8.0)
		e = c * (1 + 2.0/8.0)
		f = c * (1 + 2.5/8.0)
		g = c * (1 + 4.0/8.0)
		a = c * (1 + 5.5/8.0)
	)

	pause := TriangleTone(0)

	player.Play(time.Second/4, TriangleTone(c))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(c))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(a))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(a))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/2, TriangleTone(g))
	player.Play(time.Second/16, pause)

	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(d))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(d))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/2, TriangleTone(c))
	player.Play(time.Second/16, pause)

	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/2, TriangleTone(d))
	player.Play(time.Second/16, pause)

	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/2, TriangleTone(d))
	player.Play(time.Second/16, pause)

	player.Play(time.Second/4, TriangleTone(c))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(c))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(g))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(a))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(a))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/2, TriangleTone(g))
	player.Play(time.Second/16, pause)

	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(f))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(e))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(d))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/4, TriangleTone(d))
	player.Play(time.Second/16, pause)
	player.Play(time.Second/2, TriangleTone(c))
	player.Play(time.Second/16, pause)
}
